# Generated by Django 3.2.5 on 2024-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0002_alter_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('showaddress', models.CharField(max_length=100)),
                ('showphotos', models.ImageField(upload_to='workimages/')),
                ('showregno', models.CharField(max_length=50)),
                ('showlicense', models.ImageField(upload_to='worklicense/')),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('workaddress', models.CharField(max_length=100)),
                ('workphotos', models.ImageField(upload_to='workimages/')),
                ('workregno', models.CharField(max_length=50)),
                ('worklicense', models.ImageField(upload_to='worklicense/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
