# Generated by Django 4.2.3 on 2024-11-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0010_bikesell_carsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikerent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('km', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('rentamount', models.IntegerField()),
                ('rentalperiod', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='carrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.IntegerField()),
                ('year', models.IntegerField()),
                ('fuel', models.CharField(max_length=50)),
                ('km', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('rentamount', models.IntegerField()),
                ('rentalperiod', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
