# Generated by Django 4.2.5 on 2024-11-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0011_bikesell_rename_carssell_carsell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='brand',
            field=models.CharField(max_length=50),
        ),
    ]
