# Generated by Django 4.2.5 on 2024-12-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0011_bikerent_carrent'),
        ('CB_TARS', '0012_alter_carsell_brand'),
    ]

    operations = [
    ]
