# Generated by Django 4.2.5 on 2024-12-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0014_bikerent_model_bikesell_model_carrent_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
