# Generated by Django 4.2.5 on 2024-12-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0015_spare_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
