# Generated by Django 4.2.5 on 2024-12-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0016_alter_carsell_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='owners',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
