# Generated by Django 4.2.5 on 2024-12-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0018_alter_carsell_description_alter_carsell_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
