# Generated by Django 5.1.2 on 2025-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0019_alter_carrent_brand_alter_carsell_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesell',
            name='brand',
            field=models.CharField(max_length=50),
        ),
    ]
