# Generated by Django 5.1.2 on 2025-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0021_carsell_location_carsell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='price',
            field=models.IntegerField(),
        ),
    ]
