# Generated by Django 5.1.2 on 2025-01-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0022_alter_carsell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesell',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bikesell',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
