# Generated by Django 5.1.5 on 2025-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0026_bookingcarsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('demail', models.EmailField(max_length=254)),
                ('date', models.DateField(null=True)),
                ('price', models.CharField(max_length=30)),
            ],
        ),
    ]
