# Generated by Django 5.1.5 on 2025-01-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0027_pay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pay',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='bookingcarsell',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingcarsell',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingcarsell',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingcarsell',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookingcarsell',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
