# Generated by Django 5.1.5 on 2025-01-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0028_delete_pay_remove_bookingcarsell_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='username',
        ),
        migrations.AlterField(
            model_name='bookingcarsell',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
