# Generated by Django 5.1.5 on 2025-01-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0029_remove_bookingcarsell_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsell',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user'),
        ),
    ]
