# Generated by Django 5.1.5 on 2025-01-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0030_carsell_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsell',
            name='bookingstatus',
            field=models.CharField(blank=True, choices=[('BOOK', 'book'), ('BOOKED', 'booked')], default='book', max_length=10, null=True),
        ),
    ]
