# Generated by Django 5.1.5 on 2025-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0032_car_selling_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='bookingcarsell',
            name='razorpay_signature',
        ),
    ]
