# Generated by Django 4.2.5 on 2025-01-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0033_remove_bookingcarsell_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedcarbuyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.carsell')),
            ],
        ),
    ]
