# Generated by Django 4.2.18 on 2025-02-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0036_bookingcarsell_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerent',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
