# Generated by Django 4.2.18 on 2025-02-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0037_alter_bikerent_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user'),
        ),
    ]
