# Generated by Django 4.2.18 on 2025-02-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0038_carrent_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerent',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user'),
        ),
    ]
