# Generated by Django 4.2.18 on 2025-02-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0039_bikerent_usr'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCarRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.carrent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
    ]
