# Generated by Django 4.2.18 on 2025-02-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0040_bookingcarrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcarrent',
            name='approval_status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingcarrent',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingcarrent',
            name='startdate',
            field=models.DateField(),
        ),
    ]
