# Generated by Django 4.2.18 on 2025-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0041_bookingcarrent_approval_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='rentalperiod',
        ),
        migrations.AddField(
            model_name='bookingcarrent',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrent',
            name='rentalperiod_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrent',
            name='rentalperiod_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
