# Generated by Django 4.2.18 on 2025-02-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0042_remove_carrent_rentalperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikesell',
            name='bookingstatus',
            field=models.CharField(blank=True, choices=[('BOOK', 'book'), ('BOOKED', 'booked')], default='book', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bikesell',
            name='soldoutstatus',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'available'), ('UNAVAILABLE', 'unavailable'), ('SOLDOUT', 'soldout')], default='available', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='bikesell',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user'),
        ),
    ]
