# Generated by Django 5.1.4 on 2025-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0043_bikesell_bookingstatus_bikesell_soldoutstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrent',
            name='rentalperiod_end',
        ),
        migrations.RemoveField(
            model_name='carrent',
            name='rentalperiod_start',
        ),
        migrations.AlterField(
            model_name='bookingcarrent',
            name='totalprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
