# Generated by Django 5.1.4 on 2025-02-16 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0045_approvedcarrenters_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_renting_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order_id', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.carrent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
