# Generated by Django 5.1.4 on 2025-02-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0048_approvedbikebuyers_approvedbikerenters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedbikebuyers',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.bikesell'),
        ),
    ]
