# Generated by Django 5.1.4 on 2025-02-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0049_alter_approvedbikebuyers_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikerent',
            name='rentalperiod',
        ),
    ]
