# Generated by Django 5.1 on 2025-02-20 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0051_alter_bookingbikerent_bike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(max_length=50)),
                ('service_id', models.IntegerField(unique=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.work')),
            ],
        ),
    ]
