# Generated by Django 5.1 on 2025-02-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0052_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='price_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
