# Generated by Django 5.1.6 on 2025-02-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0054_bike_renting_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedbikerenters',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.bikerent'),
        ),
    ]
