# Generated by Django 5.1.4 on 2025-02-25 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0055_alter_approvedbikerenters_bike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike_renting_transactions',
            name='car',
        ),
        migrations.AddField(
            model_name='bike_renting_transactions',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.bikerent'),
        ),
    ]
