# Generated by Django 5.1.2 on 2025-03-02 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0058_bookingworkshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedworkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
        migrations.CreateModel(
            name='S_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.TextField(max_length=50)),
                ('service_id', models.IntegerField(unique=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.show')),
            ],
        ),
        migrations.CreateModel(
            name='Bookingshowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('approval_status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.s_services')),
            ],
        ),
    ]
