# Generated by Django 5.1.2 on 2025-03-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0060_workpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpost',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
