# Generated by Django 5.1.6 on 2025-03-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0062_showpost_sparepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvedshowroomss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.s_services')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
    ]
