# Generated by Django 5.1.6 on 2025-03-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0063_approvedshowroomss'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrent',
            name='availability',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
