# Generated by Django 5.1.6 on 2025-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0064_carrent_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrent',
            name='availability',
            field=models.CharField(blank=True, default='Available', max_length=20, null=True),
        ),
    ]
