# Generated by Django 4.2.5 on 2025-03-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0067_bike_renting_transactions_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='phoneno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='workername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
