# Generated by Django 4.2.5 on 2025-03-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0068_services_phoneno_services_workername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingtestdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('approval_status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('testdrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.showpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
        migrations.CreateModel(
            name='Approvedtestdrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('testdrive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.showpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB_TARS.user')),
            ],
        ),
    ]
