# Generated by Django 4.2.5 on 2025-03-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0069_bookingtestdrive_approvedtestdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtestdrive',
            name='date',
            field=models.DateField(),
        ),
    ]
