# Generated by Django 5.1.2 on 2025-03-11 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0070_alter_bookingtestdrive_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='workpost',
        ),
    ]
