# Generated by Django 5.1.2 on 2025-03-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0071_delete_workpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerent',
            name='availability',
            field=models.CharField(blank=True, default='Available', max_length=20, null=True),
        ),
    ]
