# Generated by Django 5.1.2 on 2025-03-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0072_bikerent_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='workregno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
