# Generated by Django 5.1.2 on 2025-03-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0073_alter_work_workregno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='showregno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
