# Generated by Django 5.1.2 on 2025-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB_TARS', '0074_alter_show_showregno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spare',
            name='spareregno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
